# Generated by Django 6.0.6 on 2026-07-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_calificacion_pedido_comprador_nivel_comprador_puntos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprador',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tiempo_entrega_dias',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
