# Generated by Django 6.0.6 on 2026-07-15 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plansuscripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.URLField(blank=True, help_text='URL de la imagen del curso (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='plan_requerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='core.plansuscripcion'),
        ),
        migrations.AddField(
            model_name='plansuscripcion',
            name='tipo',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('vendedor', 'Vendedor')], default='empresa', max_length=20),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='core.vendedor'),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to='core.empresa'),
        ),
    ]
