# Generated by Django 6.0.6 on 2026-07-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_curso_imagen_curso_plan_requerido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='stock_reservado',
            field=models.IntegerField(default=0, help_text='Unidades comprometidas en pedidos aceptados pendientes de despacho'),
        ),
    ]
