# Generated by Django 4.2.13 on 2026-07-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inventario_stock_reservado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='pagos_comprobantes/'),
        ),
    ]
