# Generated by Django 6.0.6 on 2026-07-15 02:02

import django.db.models.deletion
from django.db import migrations, models


def migrar_estados_pedido(apps, schema_editor):
    """Renombra los estados de pedido antiguos a los nuevos nombres del flujo."""
    Pedido = apps.get_model('core', 'Pedido')
    Pedido.objects.filter(estado='creado').update(estado='pendiente')
    Pedido.objects.filter(estado='confirmado').update(estado='aceptado')


def revertir_estados_pedido(apps, schema_editor):
    Pedido = apps.get_model('core', 'Pedido')
    Pedido.objects.filter(estado='pendiente').update(estado='creado')
    Pedido.objects.filter(estado='aceptado').update(estado='confirmado')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_administrador_options_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_estados_pedido, revertir_estados_pedido),
        migrations.AddField(
            model_name='calificacion',
            name='estado_incidencia',
            field=models.CharField(blank=True, choices=[('', 'No es incidencia'), ('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='resolucion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='motivo_rechazo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido'), ('bloqueado', 'Bloqueado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('preparando', 'Preparando'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido'), ('bloqueado', 'Bloqueado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='SolicitudColaboracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_colaboracion', to='core.empresa')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_colaboracion', to='core.vendedor')),
            ],
            options={
                'verbose_name': 'Solicitud de colaboración',
                'verbose_name_plural': 'Solicitudes de colaboración',
                'unique_together': {('vendedor', 'empresa')},
            },
        ),
    ]
