# Generated by Django 6.0.6 on 2026-07-15 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_calificacion_estado_incidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='core.pedido'),
        ),
        migrations.AddField(
            model_name='comprador',
            name='nivel',
            field=models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('diamante', 'Diamante')], default='bronce', max_length=20),
        ),
        migrations.AddField(
            model_name='comprador',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='DireccionEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('predeterminada', models.BooleanField(default=False)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='core.comprador')),
            ],
            options={
                'verbose_name': 'Dirección de entrega',
                'verbose_name_plural': 'Direcciones de entrega',
            },
        ),
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('motivo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_puntos', to='core.comprador')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_puntos', to='core.pedido')),
            ],
            options={
                'verbose_name': 'Movimiento de puntos',
                'verbose_name_plural': 'Movimientos de puntos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('nivel_minimo', models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('diamante', 'Diamante')], default='bronce', max_length=20)),
                ('descuento_porcentaje', models.FloatField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
            },
        ),
    ]
