# Generated by Django 6.0.6 on 2026-07-15 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_calificacion_devolucion_autorizada_pedido_descuento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duracion_meses', models.IntegerField(default=1, help_text='Duración en meses del plan')),
                ('comision_plataforma', models.FloatField(default=5.0, help_text='Porcentaje de comisión para la plataforma')),
                ('beneficios', models.TextField(blank=True, help_text='Beneficios incluidos, separados por comas o líneas')),
                ('limite_productos', models.IntegerField(default=100, help_text='Límite máximo de productos activos')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de Suscripción',
                'verbose_name_plural': 'Planes de Suscripción',
            },
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='comision_plataforma',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='tipo_plan',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suscripciones_empresas', to='core.plansuscripcion'),
        ),
    ]
